include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    type_annotate_public_apis: false
    cascade_invocations: false
    require_trailing_commas: false
    prefer_final_locals: false
    avoid_returning_null_for_void: false
