name: blog_api
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  dio: ^4.0.6
  json_annotation: ^4.8.0
  logger: ^1.1.0
  retrofit: ^3.3.1

dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.6.0
  retrofit_generator: ^4.2.0
  very_good_analysis: ^3.1.0

