name: cache_client
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  auth_repository:
    path: ../auth_repository
  hive: ^2.2.3
  path_provider: ^2.0.11

dev_dependencies:
  build_runner: ^2.3.3
  hive_generator: ^2.0.0
  very_good_analysis: ^3.1.0
