name: posts_repository
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  blog_api:
    path: ../blog_api
  dio: ^4.0.6
  equatable: ^2.0.5

dev_dependencies:
  very_good_analysis: ^3.1.0
